//
// Main+EmptyEnvironmentEffect.swift
// Raptor
// https://raptor.build
// See LICENSE for license information.
//

public extension Main {
    /// A proxy that defines page-level styles for an environment condition.
    struct EmptyEnvironmentEffect {
        /// The CSS properties generated by this proxy.
        var properties: [Property] = []

        /// Sets the page’s background color for the current environment condition.
        /// - Parameter color: The color to apply. Passing `nil` has no effect.
        /// - Returns: A modified proxy with the background color applied.
        public func background(_ color: Color) -> Self {
            var copy = self
            copy.properties.append(.variable("bg-page", value: color.description))
            return copy
        }

        /// Sets the page’s background gradient for the current environment condition.
        /// - Parameter gradient: The gradient to apply. Passing `nil` has no effect.
        /// - Returns: A modified proxy with the background gradient applied.
        public func background(_ gradient: Gradient) -> Self {
            var copy = self
            copy.properties.append(.variable("bg-gradient", value: gradient.description))
            return copy
        }
    }
}
