//
// MetaTag.swift
// Raptor
// https://raptor.build
// See LICENSE for license information.
//

import Foundation

/// An item of metadata that helps browsers and search engines understand
/// your page better.
struct Metadata: HeadContent, Sendable {
    /// Metadata names for social media cards.
    public enum `Type`: String, Sendable {
        /// The image to display in Twitter cards.
        case twitterImage = "twitter:image"
        /// The title to display in Twitter cards.
        case twitterTitle = "twitter:title"
        /// The domain to display in Twitter cards.
        case twitterDomain = "twitter:domain"
        /// The type of Twitter card to use.
        case twitterCard = "twitter:card"
        /// Whether to disable Twitter tracking.
        case twitterDoNotTrack = "twitter:dnt"
        /// The description to display in Twitter cards.
        case twitterDescription = "twitter:description"
        /// The software used to generate the document.
        case generator
        /// The viewport configuration for responsive web design.
        case viewport

        /// The title of the shared content.
        case openGraphTitle = "og:title"
        /// A description of the shared content.
        case openGraphDescription = "og:description"
        /// The image to display when sharing.
        case openGraphImage = "og:image"
        /// The canonical URL of the shared content.
        case openGraphURL = "og:url"
        /// The name of the website.
        case openGraphSiteName = "og:site_name"

        /// The meta attribute key.
        var key: String {
            switch self {
            case .twitterImage, .twitterTitle, .twitterDomain, .twitterCard,
                 .twitterDoNotTrack, .twitterDescription, .generator, .viewport:
                "name"
            case .openGraphTitle, .openGraphDescription, .openGraphImage,
                 .openGraphURL, .openGraphSiteName:
                "property"
            }
        }
    }

    /// Allows mobile browsers to scale this page appropriately for the device.
    static let flexibleViewport = Metadata(.viewport, content: "width=device-width, initial-scale=1")

    /// Marks this page as using UTF-8 content.
    static let utf8 = Metadata(characterSet: "utf-8")

    /// Marks this page as having been automatically generated by Raptor.
    static let generator = Metadata(.generator, content: Raptor.version)

    /// The standard set of control attributes for HTML elements.
    var attributes = CoreAttributes()

    /// A convenience initializer for when you want a piece of data with a
    /// URL as its content. Creates a new `MetaTag` instance from the type
    /// and URL provided.
    /// - Parameters:
    ///   - type: The type of metadata.
    ///   - content: The URL value for the metadata.
    init(_ type: `Type`, content: URL) {
        self.init(type, content: content.absoluteString)
    }

    /// Creates a new `MetaTag` instance from a metadata type and content provided.
    /// - Parameters:
    ///   - type: The type of metadata.
    ///   - content: The value for the metadata.
    init(_ type: `Type`, content: String) {
        attributes.append(customAttributes: .init(name: type.key, value: type.rawValue))
        attributes.append(customAttributes: .init(name: "content", value: content))
    }

    /// Creates a new `MetaTag` instance from the custom name and content provided.
    /// - Parameters:
    ///   - name: The name for the metadata.
    ///   - content: The value for the metadata.
    init(name: String, content: String) {
        attributes.append(customAttributes: .init(name: "name", value: name))
        attributes.append(customAttributes: .init(name: "content", value: content))
    }

    /// Creates a new `MetaTag` instance from the custom property and content provided.
    /// - Parameters:
    ///   - property: The property name for the metadata.
    ///   - content: The value for the metadata.
    init(property: String, content: String) {
        attributes.append(customAttributes: .init(name: "property", value: property))
        attributes.append(customAttributes: .init(name: "content", value: content))
    }

    /// Creates a new piece of metadata that sets a specific character set for
    /// the current page.
    /// - Parameter characterSet: The value for the character set.
    init(characterSet: String) {
        attributes.append(customAttributes: .init(name: "charset", value: characterSet))
    }

    /// Creates a new `MetaTag` instance for HTTP equivalent headers.
    /// - Parameters:
    ///   - httpEquivalent: The HTTP header to simulate
    ///   - content: The value for the header
    init(httpEquivalent: String, content: String) {
        attributes.append(customAttributes: .init(name: "http-equiv", value: httpEquivalent))
        attributes.append(customAttributes: .init(name: "content", value: content))
    }

    /// Returns a standard set of social sharing metadata for a given page,
    /// including the page title, description, and image.
    /// - Returns: An array of `MetaTag` objects that should be placed
    /// into your page header to enable social sharing.
    public static func socialSharingTags() -> [Metadata] {
        guard let context = RenderingContext.current else {
            fatalError("""
            Failed to access the PageContext while generating social sharing tags.
            Please file a bug report with the Raptor project.
            """)
        }

        let site = context.site
        let page = context.environment.page

        var metadata = [Metadata(.openGraphSiteName, content: site.name)]

        if let image = page.image {
            metadata.append(.init(.openGraphImage, content: image))
            metadata.append(.init(.twitterImage, content: image))
        }

        let pageTitle = page.title
        metadata.append(.init(.openGraphTitle, content: pageTitle))
        metadata.append(.init(.twitterTitle, content: pageTitle))

        let pageDescription = page.description
        if pageDescription.isEmpty == false {
            metadata.append(.init(.openGraphDescription, content: pageDescription))
            metadata.append(.init(.twitterDescription, content: pageDescription))
        }

        let pageURL = page.url
        metadata.append(.init(.openGraphURL, content: pageURL))

        if let domain = pageURL.removingWWW {
            metadata.append(.init(.twitterDomain, content: domain))
        }

        metadata.append(.init(.twitterCard, content: "summary_large_image"))
        metadata.append(.init(.twitterDoNotTrack, content: "on"))

        return metadata
    }

    /// Renders this element into HTML.
    /// - Returns: The HTML for this element.
    public func render() -> Markup {
        Markup("<meta\(attributes) />")
    }
}

extension Metadata {
    /// Adds a data attribute to the element.
    /// - Parameters:
    ///   - name: The name of the data attribute
    ///   - value: The value of the data attribute
    /// - Returns: The modified `MetaTag`
    func data(_ name: String, _ value: String) -> Self {
        var copy = self
        copy.attributes.data.append(.init(name: name, value: value))
        return copy
    }

    /// Adds a custom attribute to the element.
    /// - Parameters:
    ///   - name: The name of the custom attribute
    ///   - value: The value of the custom attribute
    /// - Returns: The modified `HTML` element
    func customAttribute(name: String, value: String) -> Self {
        var copy = self
        copy.attributes.append(customAttributes: .init(name: name, value: value))
        return copy
    }
}
